Task 2
mrbialas1/invoicing-system-piotr-bialas pull request #3
Opened 2023-04-07 11:02 UTC by mrbialas1

Zrobione ale problem z akcjami na zielono

2023-04-14 17:52 UTC, strzeleckik requested changes
Poprawiłem ci problem z github actions, ładnie się teraz po stronie github buduje (przeanalizuj moje commity). Do zaliczenia zadania brakuje Ci realizacji w zasadzie całego pkt. 6

2023-04-24 17:35 UTC, strzeleckik commented on src/main/java/pl/project/invoicing/db/memory/InMemoryDatabase.java
> +public class InMemoryDatabase {
brakuje implementacji

2023-04-24 17:35 UTC, strzeleckik commented on src/main/java/pl/project/invoicing/model/Company.java
> +
użyj Lomboka :)

2023-04-24 17:35 UTC, strzeleckik commented on src/main/java/pl/project/invoicing/model/InvoiceEntry.java
> +
Lombok

2023-04-24 17:36 UTC, strzeleckik commented on src/main/java/pl/project/invoicing/utils/TextUtils.java
> +public class TextUtils {
ta klasa jest nie potrzebna

2023-04-24 17:36 UTC, strzeleckik commented on src/main/java/pl/project/invoicing/model/Invoice.java
> +  //private List<InvoiceEntry> entries;
dlaczego wykomentowane?

2023-04-24 17:39 UTC, strzeleckik requested changes
Kilka uwag dodałem, zerknij sobie na wzorcowy projekt jak masz problemy: https://github.com/passionate-software-engineer/invocing-system-piotr-kolacz/pulls
(task_2 / task_3)

2023-05-01 12:34 UTC, mrbialas1 commented
Błąd z plikiem checkstyle.xml. Jakieś rady do jego edycji aby nie upominał się o te niezbyt potrzebne puste linijki?

2023-05-03 19:13 UTC, strzeleckik requested changes
Checkstyles się wysypuje - dlatego psuje się build w github actions ;) musisz poprawić formatowanie kodu w 3 plikach :)

2023-05-09 10:19 UTC, strzeleckik approved these changes
ok

2023-05-09 11:08 UTC, merged